public with sharing class DIBenchClass {
    public class Benchmark1 {
    }
    public class Benchmark2 {
    }
    public class Benchmark3 {
    }
    public class Benchmark4 {
    }
    public class Benchmark5 {
    }
    public class Benchmark6 {
    }
    public class Benchmark7 {
    }
    public class Benchmark8 {
    }
    public class Benchmark9 {
    }
    public class Benchmark10 {
    }
    public class Benchmark11 {
    }
    public class Benchmark12 {
    }
    public class Benchmark13 {
    }
    public class Benchmark14 {
    }
    public class Benchmark15 {
    }
    public class Benchmark16 {
    }
    public class Benchmark17 {
    }
    public class Benchmark18 {
    }
    public class Benchmark19 {
    }
    public class Benchmark20 {
    }
    public class Benchmark21 {
    }
    public class Benchmark22 {
    }
    public class Benchmark23 {
    }
    public class Benchmark24 {
    }
    public class Benchmark25 {
    }
    public class Benchmark26 {
    }
    public class Benchmark27 {
    }
    public class Benchmark28 {
    }
    public class Benchmark29 {
    }
    public class Benchmark30 {
    }
    public class Benchmark31 {
    }
    public class Benchmark32 {
    }
    public class Benchmark33 {
    }
    public class Benchmark34 {
    }
    public class Benchmark35 {
    }
    public class Benchmark36 {
    }
    public class Benchmark37 {
    }
    public class Benchmark38 {
    }
    public class Benchmark39 {
    }
    public class Benchmark40 {
    }
    public class Benchmark41 {
    }
    public class Benchmark42 {
    }
    public class Benchmark43 {
    }
    public class Benchmark44 {
    }
    public class Benchmark45 {
    }
    public class Benchmark46 {
    }
    public class Benchmark47 {
    }
    public class Benchmark48 {
    }
    public class Benchmark49 {
    }
    public class Benchmark50 {
    }
    public class Benchmark51 {
    }
    public class Benchmark52 {
    }
    public class Benchmark53 {
    }
    public class Benchmark54 {
    }
    public class Benchmark55 {
    }
    public class Benchmark56 {
    }
    public class Benchmark57 {
    }
    public class Benchmark58 {
    }
    public class Benchmark59 {
    }
    public class Benchmark60 {
    }
    public class Benchmark61 {
    }
    public class Benchmark62 {
    }
    public class Benchmark63 {
    }
    public class Benchmark64 {
    }
    public class Benchmark65 {
    }
    public class Benchmark66 {
    }
    public class Benchmark67 {
    }
    public class Benchmark68 {
    }
    public class Benchmark69 {
    }
    public class Benchmark70 {
    }
    public class Benchmark71 {
    }
    public class Benchmark72 {
    }
    public class Benchmark73 {
    }
    public class Benchmark74 {
    }
    public class Benchmark75 {
    }
    public class Benchmark76 {
    }
    public class Benchmark77 {
    }
    public class Benchmark78 {
    }
    public class Benchmark79 {
    }
    public class Benchmark80 {
    }
    public class Benchmark81 {
    }
    public class Benchmark82 {
    }
    public class Benchmark83 {
    }
    public class Benchmark84 {
    }
    public class Benchmark85 {
    }
    public class Benchmark86 {
    }
    public class Benchmark87 {
    }
    public class Benchmark88 {
    }
    public class Benchmark89 {
    }
    public class Benchmark90 {
    }
    public class Benchmark91 {
    }
    public class Benchmark92 {
    }
    public class Benchmark93 {
    }
    public class Benchmark94 {
    }
    public class Benchmark95 {
    }
    public class Benchmark96 {
    }
    public class Benchmark97 {
    }
    public class Benchmark98 {
    }
    public class Benchmark99 {
    }
    public class Benchmark100 {
    }
    public class Benchmark101 {
    }
    public class Benchmark102 {
    }
    public class Benchmark103 {
    }
    public class Benchmark104 {
    }
    public class Benchmark105 {
    }
    public class Benchmark106 {
    }
    public class Benchmark107 {
    }
    public class Benchmark108 {
    }
    public class Benchmark109 {
    }
    public class Benchmark110 {
    }
}